<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="19573" started-at="2019-04-04T06:36:09Z" finished-at="2019-04-04T06:36:29Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="19573" started-at="2019-04-04T06:36:09Z" finished-at="2019-04-04T06:36:29Z">
      <class name="com.training.sanity.tests.CYTC_072_Member_Database">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.CYTC_072_Member_Database@4883b407]" name="setUpBeforeClass" is-config="true" duration-ms="0" started-at="2019-04-04T06:36:10Z" finished-at="2019-04-04T06:36:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="FAIL" signature="Validate_Login(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.CYTC_072_Member_Database@4883b407]" name="Validate_Login" duration-ms="564" started-at="2019-04-04T06:36:10Z" data-provider="excel-inputs" finished-at="2019-04-04T06:36:10Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: Validate_Login([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Shona,(java.lang.String) Shona3623,(java.lang.String) manzoor,(java.lang.String) manzoor,(java.lang.String) 50.0,(java.lang.String) Debit to member,(java.lang.String) Bonus]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: Validate_Login([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Shona,(java.lang.String) Shona3623,(java.lang.String) manzoor,(java.lang.String) manzoor,(java.lang.String) 50.0,(java.lang.String) Debit to member,(java.lang.String) Bonus]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validate_Login -->
        <test-method status="PASS" signature="set()[pri:0, instance:com.training.sanity.tests.CYTC_072_Member_Database@4883b407]" name="set" is-config="true" duration-ms="8967" started-at="2019-04-04T06:36:10Z" finished-at="2019-04-04T06:36:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="loginDBTest(java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.CYTC_072_Member_Database@4883b407]" name="loginDBTest" duration-ms="7679" started-at="2019-04-04T06:36:19Z" data-provider="db-inputs" finished-at="2019-04-04T06:36:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Shona]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Shona3623]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDBTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.CYTC_072_Member_Database@4883b407]" name="tearDown" is-config="true" duration-ms="2134" started-at="2019-04-04T06:36:27Z" finished-at="2019-04-04T06:36:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.CYTC_072_Member_Database -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
